#!/bin/bash

# --- Script Configuration ---
# Define input and output directories.
# Using variables makes the script easier to maintain.
INPUT_DIR="Bulk_RNASeq_analysis"
OUTPUT_DIR="fastp_results"

# Set the number of threads for fastp.
# Modify this according to your server's hardware configuration.
THREADS=12

# --- Preparatory Steps ---

# 1. Check if the fastp command is available.
# 'command -v' checks if a command exists in the system's PATH.
# '&> /dev/null' redirects both standard output and standard error to a "black hole", meaning no messages will be displayed.
if ! command -v fastp &> /dev/null; then
    echo "Error: 'fastp' command not found. Please ensure fastp is installed and in your PATH."
    exit 1
fi

# 2. Check if the input directory exists.
if [ ! -d "$INPUT_DIR" ]; then
    echo "Error: Input directory '$INPUT_DIR' does not exist."
    exit 1
fi

# 3. Create the output directory.
# 'mkdir -p' creates the directory and does not report an error if it already exists.
echo "Creating output directory: $OUTPUT_DIR"
mkdir -p "$OUTPUT_DIR"

# --- Core Processing Logic ---

# 4. Loop through all R1 files to identify unique sample groups.
# This is the most reliable method, as every valid sample pair must have an R1 file.
for r1_file in "$INPUT_DIR"/*_1.fq.gz; do
    
    # Check if the loop found any files. If no files match, globbing returns the pattern itself.
    if [ ! -f "$r1_file" ]; then
        echo "Warning: No files matching '*_1.fq.gz' were found in the '$INPUT_DIR' directory."
        break # Exit the loop
    fi

    # 5. Extract the group name/prefix from the R1 filename.
    #   - `basename "$r1_file"` gets the filename, e.g., E250098172_L01_ZHW-C1_1.fq.gz
    #   - `sed 's/_1.fq.gz//'` uses the sed command to remove the suffix, yielding the group name, e.g., E250098172_L01_ZHW-C1
    group_name=$(basename "$r1_file" | sed 's/_1.fq.gz//')

    # 6. Construct the full path for the corresponding R2 file based on the group name.
    r2_file="${INPUT_DIR}/${group_name}_2.fq.gz"

    # 7. Robustness check: Confirm that the corresponding R2 file exists.
    if [ ! -f "$r2_file" ]; then
        echo "Warning: Found '$r1_file' but could not find its pair '$r2_file'. Skipping sample group: $group_name"
        continue # Skip the current iteration and proceed to the next sample
    fi

    echo "--------------------------------------------------"
    echo "Processing sample group: $group_name"
    echo "R1 Input: $r1_file"
    echo "R2 Input: $r2_file"

    # 8. Construct the paths and names for the output files.
    # It's good practice to add "clean" or "trimmed" to output filenames to distinguish them from the original files.
    output_r1="${OUTPUT_DIR}/${group_name}_clean_1.fq.gz"
    output_r2="${OUTPUT_DIR}/${group_name}_clean_2.fq.gz"
    
    # Construct the paths for the report files generated by fastp.
    html_report="${OUTPUT_DIR}/${group_name}.html"
    json_report="${OUTPUT_DIR}/${group_name}.json"

    # 9. Execute the fastp command.
    fastp \
        -i "$r1_file" \
        -I "$r2_file" \
        -o "$output_r1" \
        -O "$output_r2" \
        -h "$html_report" \
        -j "$json_report" \
        -w "$THREADS" # Use the predefined number of threads

    echo "Sample group $group_name processing complete."
    echo "--------------------------------------------------"
    echo "" # Add an empty line for clearer output

done

echo "All samples processed! Results are saved in the '$OUTPUT_DIR' directory."